FROM openjdk:17-jdk-slim

ARG DB_URL
ENV DB_URL ${DB_URL}

ARG DB_USERNAME
ENV DB_USERNAME ${DB_USERNAME}

ARG DB_PASSWORD
ENV DB_PASSWORD ${DB_PASSWORD}

ARG DB_NAME
ENV DB_NAME ${DB_NAME}

ARG JWT_SECRET
ENV JWT_SECRET ${JWT_SECRET}

ARG GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_ID ${GOOGLE_CLIENT_ID}

ARG GOOGLE_CLIENT_SECRET
ENV GOOGLE_CLIENT_SECRET ${GOOGLE_CLIENT_SECRET}

ARG GOOGLE_REDIRECT_URI
ENV GOOGLE_REDIRECT_URI ${GOOGLE_REDIRECT_URI}

EXPOSE 8080
ENV TZ=Asia/Seoul
COPY build/libs/*.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
