FROM openjdk:17-jdk-slim

ARG MYSQL_USERNAME
ARG MYSQL_PASSWORD

ENV MYSQL_USERNAME ${MYSQL_USERNAME}
ENV MYSQL_PASSWORD ${MYSQL_PASSWORD}

EXPOSE 8080
ENV TZ=Asia/Seoul
COPY build/libs/*.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
